title: Shubham Mohole
email: sam588@cornell.edu
description: >-
  Computer Science student at Cornell University. Research in machine learning, 
  privacy-preserving systems, and AI safety.
baseurl: ""
url: "https://shub500.github.io"
github_username: Shub500

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Custom navigation - specify which pages to show in header
header_pages:
  - publications.md
  - research.md

# Disable showing posts on the home page
show_excerpts: false

# Include assets
include:
  - assets

markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - about.markdown